### ISSUE TITLE
How to cancel or modify the invitation ? 

### ISSUE THREAD

**Issue by Julien22bzh** [MadeiraData/sql-clr-ics#21]
Hi Eitan,
how are you ?

I want to cancel or modify the invitation. But I can't do it.
How do I send the EvenID parameter in the cancel or modify request ? there is no parameter for this.

Thanks,
Julien.

**Comment by EitanBlumin** [comment]
Hi @Julien22bzh ,
There actually is a parameter to update or cancel an existing EventId. It's the same one which is also an output parameter. Please see the README for more details.

Unfortunately, though, the cancellation doesn't work quite right as of yet and I don't know why.
There's an open issue about this already: #11
